/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PositionTarget {
  blockId: number
  index: number
}
export interface SiblingNode {
  hash: Buffer
  direction: string
}
export interface MerkleProof {
  path: Array<SiblingNode>
}
export declare function derivePathChain(seed: number, numBlockGroups: number, proofBytes: Buffer): Array<PositionTarget>
export declare function verifyInclusionProof(selfFragment: Buffer, proofPath: Array<SiblingNode>, expectedRootHash: Buffer): boolean
export declare function verifyTimeBound(timestampDiffMs: number): boolean
